language: python
python:
  - "3.5"
  - "3.6"
  - "2.7"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - pip install --upgrade pip

install:
  - pip install flake8
  - pip install .

script:
  - flake8 funfolding
  - python setup.py test
